<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>App</title>
        <style>
            body {
                background-color: #F5F5F5;
                font-size: 13px;
                font-family: Arial;
                color: #414141;            
            }
            .social {
                padding-right:10px;
                padding-top:10px;
                display: block;
                vertical-align: middle;
            }
            .profile {
                display: none;
                vertical-align: middle;
                background-color: white;
                border: 1px solid #bdc4cc;
                border-radius: 5px;
                padding: 9px;
                width: 180px;
                word-break: break-word;
            }
            .name {
                display: inline-table;
                vertical-align: top;
                font-size: 14px;
            }
            .ava {
                display: inline-table;
                margin-left: 10px;
            }
            .ava src {
                width:30px;
            }
            #content {
                width: 100px;
                height: 100px;
                position: absolute;
                top:0;
                bottom: 0;
                left: 0;
                right: 0;
                margin: auto;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="/js/loading.js"></script>
    </head>
    <body>
    <script>
    
    function drawProfile(response){
        $('.name').html('<p>'+response.first_name+' '+response.last_name+'</p>');
        $('.ava').html('<img src="'+response.picture.data.url+'" width="40px">');
        $('.profile').show();
    }    
    
    function statusChangeCallback(response) {
       if (response.status === 'connected') {
           FB.api('/me', 'get', {fields:['first_name','last_name', 'picture']}, function(response) {
               drawProfile(response);               
               $.get('/authorize');
           });
       } else {
           $('.profile').hide();
       }
    }

    function checkLoginState() {
        FB.getLoginStatus(function(response) {
            statusChangeCallback(response);
        });
    }


    $(document).ready(function(){
        $.ajaxSetup({ cache: true });
        $.getScript('//connect.facebook.net/en_US/sdk.js', function(){
            FB.init({
                appId: '<?php echo $app_id; ?>',
                cookie     : true,
                xfbml      : true,
                version: 'v2.8'
            });     
            $('#loginbutton,#feedbutton').removeAttr('disabled');
            FB.getLoginStatus(function(response) {
console.log(response);
                statusChangeCallback(response);
            });
        });
   });

   </script>
   <header>
       <div align="right">
       <div class="profile">
           <span class="name"></span>
           <span class="ava"></span>
       </div>
       <div class="social social_fb" align="right">
           <div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="true" data-use-continue-as="true" scope="public_profile, email" onlogin="checkLoginState();"></div>
       </div>
       </div>
   </header>
   <div id="content">
       content
   </div>
   <div id="status"></div>
    </body>
</html>
